### ISSUE TITLE
is compatible with Podman v5

### ISSUE THREAD

**Issue by Roeda** [tbelway/immich-podman-quadlets#1]
Hi,
thank you very much for your quadlets, it makes my life easier, as I am starting a migration from docker to podman, and still a bit a beginner in podman.
a question please, with the podman v5, quadlet seems to add parity with docker-compose in terms of "parameters" supported in the template. do we have things to add for Immich or are your quadlets sufficient and compatible with the v5 ?

thanks in advance

**Comment by tbelway** [comment]
This seems less like an issue and more like an attempted discussion. But I'm using podman v5 no issues with quadlets.
